### ISSUE TITLE
Support arm architecture

### ISSUE THREAD

**Issue by wagnst** [pschichtel/s3-backup#1]
deploying on arm (raspberry 4b) gives
`exec /backup.sh: exec format error`

please add arm support

**Comment by pschichtel** [comment]
pull requests are welcome. I think all the upstream projects (s3fs and restic) support arm just fine, the github workflow just needs to be adjusted to build my container for multiple architectures.

**Comment by pschichtel** [comment]
0.2.3 and 0.2.4 are available for arm64
